// data-testid registry for the Global AI Law Tracker
export const TRACKER = {
  // shell / nav
  themeToggle: 'theme-toggle',
  navMap: 'nav-map',
  navBrowse: 'nav-browse',
  navTimeline: 'nav-timeline',
  navCompare: 'nav-compare',
  navAssistant: 'nav-assistant',
  dataFreshnessBadge: 'data-freshness-badge',
  // map
  worldMap: 'world-map',
  usMap: 'us-map',
  mapScopeToggle: 'map-scope-toggle',
  mapLegend: 'map-legend',
  mapModeToggle: 'map-mode-toggle',
  countryPanel: 'country-panel',
  statePanel: 'state-panel',
  // admin
  adminButton: 'admin-open-button',
  adminTokenInput: 'admin-token-input',
  adminLoginButton: 'admin-login-button',
  adminAddButton: 'admin-add-button',
  adminSaveButton: 'admin-save-button',
  adminDeleteButton: 'admin-delete-button',
  adminSearchInput: 'admin-search-input',
  // stats
  statsDashboard: 'stats-dashboard',
  statTotalLaws: 'stat-total-laws',
  statJurisdictions: 'stat-jurisdictions',
  statEnacted: 'stat-enacted',
  statProposed: 'stat-proposed',
  // browse / filters
  searchInput: 'search-input',
  filterRegion: 'filter-region',
  filterStatus: 'filter-status',
  filterCategory: 'filter-category',
  filterGroup: 'filter-group',
  filterSort: 'filter-sort',
  filtersReset: 'filters-reset-button',
  exportButton: 'export-csv-button',
  shareButton: 'share-view-button',
  loadMore: 'load-more-button',
  lawGrid: 'law-grid',
  lawCard: 'law-card',
  lawStatusBadge: 'law-status-badge',
  lawCardOpen: 'law-card-open-details',
  // detail
  lawDetailDialog: 'law-detail-dialog',
  lawSourceLinks: 'law-source-links',
  lawLastVerified: 'law-last-verified',
  // timeline
  timelineView: 'timeline-view',
  // compare
  compareSelect: 'country-compare-select',
  compareTable: 'country-compare-table',
  // assistant
  assistantPanel: 'ai-assistant-panel',
  assistantInput: 'ai-assistant-input',
  assistantSend: 'ai-assistant-send-button',
  assistantMessage: 'ai-assistant-message',
  assistantSuggestion: 'ai-assistant-suggestion',
};
